class Util
    STATE_ARRAY = [
		"Alabama",
		"Alaska",
		"Arizona",
		"Arkansas",
		"California",
		"Colorado",
		"Connecticut",
		"Delaware",
		"Florida",
		"Georgia",
		"Hawaii",
		"Idaho",
		"Illinois",
		"Indiana",
		"Iowa",
		"Kansas",
		"Kentucky",
		"Louisiana",
		"Maine",
		"Maryland",
		"Massachusetts",
		"Michigan",
		"Minnesota",
		"Mississippi",
		"Missouri",
		"Montana",
		"Nebraska",
		"Nevada",
		"New Hampshire",
		"New Jersey",
		"New Mexico",
		"New York",
		"North Carolina",
		"North Dakota",
		"Ohio",
		"Oklahoma",
		"Oregon",
		"Pennsylvania",
		"Rhode Island",
		"South Carolina",
		"South Dakota",
		"Tennessee",
		"Texas",
		"Utah",
		"Vermont",
		"Virginia",
		"Washington",
		"Washington, D.C.",
		"West Virginia",
		"Wisconsin",
		"Wyoming"
	]

	WORK_SITUATIONS_ARRAY = [
		"I lost my job or am furloughed bcause of the pandemic.",
		"I lost my job or am furloughed, unrelated to the pandemic.",
		"I have reduced hours due to the pandemic.",
		"I have reduced hours, unrelated to the pandemic.",
		"I run my own business and have been forced to close or have reduced income due to the pandemic.",
		"I run my own business and have have been forced to close or have reduced income, unrelated to the pandemic.",
		"I am struggling to pay for costs associated with systemic oppression like bail.",
		"I am struggling to pay for gender reassignment surgery, hormone therapy, or other medical costs.",
		"I am struggling to pay substantial medical bills.",
		"I am struggling to pay for costs associated with raising my child(ren).",
		"I am struggling to pay for costs associated with caring for another person.",
		"I am struggling to pay an unexpected bill.",
		"I am struggling to pay my pet's veterinary bills.",
		"I am struggling financially for another reason.",
	]

	WORK_FIELDS_ARRAY = [
		"Arts",
		"Business and finance",
		"Computers, science and technology",
		"Construction",
		"Education",
		"Engineering",
		"Farming, fishing and forestry",
		"Government and public administration",
		"Health care and medical",
		"Hospitality, travel, tourism and service",
		"Law enforcement, public safety, corrections and security",
		"Legal",
		"Management",
		"Marketing and sales",
		"Media communications and broadcasting",
		"Military and armed forces",
		"Nonprofit and social services",
		"Office administration",
		"Production and manufacturing",
		"Psychology and counseling",
		"Installation, repair and maintenance",
		"Stay at home parent",
		"Transportation and moving",
		"Unemployed"
	]

	FAMILY_SIZE_ARRAY = [
		"I live by myself", 
		"2", 
		"3", 
		"4", 
		"5", 
		"6",
		"7",
		"8",
		"9",
		"10 or more" 
	]

	SELECT_AMOUNT = [
		22.5,
		45.0,
		67.5,
		90.0
	]

	SELECT_STORE = [
  "Acme",
  "Albertsons",
  "Carrs",
  "Food Lion",
  "Hannaford",
  "Jewel Osco",
  "Morton Williams",
  "Pavilions",
  "Randalls",
  "Safeway",
  "Shaw’s",
  "Star Market",
  "Tom Thumb",
  "Vons",
  "Whole Foods"
]

end